version: 2.1

jobs:
  build:
    docker:
      - image: dejac001/isotherm-fitting-tests
    steps:
      - run:
          name: Clone repository
          command: |
            cd /home/pyomo/shared/
            git clone https://github.com/dejac001/adsorption_isotherm_fitting.git
      - run:
          name: Lint with flake8
          command: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run:
          name: Run tests
          command: |
            cd /home/pyomo/shared/adsorption_isotherm_fitting/
            export PYTHONPATH=$PWD
            pytest
