FROM ubuntu

MAINTAINER Robert F. DeJaco <dejac001@umn.edu>
USER root

RUN apt-get update && apt-get -y install apt-utils
RUN DEBIAN_FRONTEND="noninteractive" \
    apt-get -y install \
        git gcc g++ gfortran patch wget pkg-config make \
        liblapack-dev libmetis-dev libmumps-dev libblas-dev
